function generateSprites() {
	
	Sprites = {
		//Line 1
		brick: [0, 0],
		stone: [1, 0],
		coal: [2, 0],
		gold: [3, 0],
		uranium: [4, 0],
		diamond: [5, 0],
		iron: [6, 0],
		silver: [7, 0],
		platinum: [8, 0],
		copper: [9, 0],
		titanium: [10, 0],
		bronze: [11, 0],
		cobble: [12, 0],
		plank: [13, 0],
		trunk: [14, 0],
		dirt: [15, 0],
		grass: [16, 0],
		sand: [17, 0],
		leaves: [18, 0],
		weed: [19, 0],
		red_flower: [20, 0],
		yellow_flower: [21, 0],
		water: [22, 0],
		slab: [23, 0],
		wood_stair: [24, 0],
		stone_stair: [25, 0],
		ladder: [26, 0],
		ice: [27, 0],
		glass: [28, 0],
		lava: [29, 0],
		gravel: [30, 0],
		
		wood_pick: [0, 1],
		stone_pick: [1, 1],
		iron_pick: [2, 1],
		diamond_pick: [3, 1],
		uranium_pick: [4, 1],
		wood_axe: [5, 1],
		stone_axe: [6, 1],
		iron_axe: [7, 1],
		diamond_axe: [8, 1],
		wood_sword: [9, 1],
		stone_sword: [10, 1],
		iron_sword: [11, 1],
		diamond_sword: [12, 1],
		
		door_closed: [0, 3, 1, 2],
		door_open: [1, 3, 1, 2],
		player: [2, 3, 1, 2]
	};
	
	SpriteMap = [
		//Line 1
		"brick",
		"stone",
		"coal",
		"gold",
		"uranium",
		"diamond",
		"iron",
		"silver",
		"platinum",
		"copper",
		"titanium",
		"bronze",
		"cobble",
		"plank",
		"trunk",
		"dirt",
		"grass",
		"sand",
		"leaves",
		"weed",
		"red_flower",
		"yellow_flower",
		"water",
		"slab",
		"wood_stair",
		"stone_stair",
		"ladder",
		"ice",
		"glass",
		"lava",
		"gravel",
		
		"wood_pick",
		"stone_pick",
		"iron_pick",
		"diamond_pick",
		"uranium_pick",
		"wood_axe",
		"stone_axe",
		"iron_axe",
		"diamond_axe",
		"wood_sword",
		"stone_sword",
		"iron_sword",
		"diamond_sword",
		
		"door_closed",
		"door_open",
		"player"
	];
	
	SpriteSettings = {
		//Line 1
		brick: {solid: true},
		stone: {solid: true},
		coal: {solid: true},
		gold: {solid: true},
		uranium: {solid: true},
		diamond: {solid: true},
		iron: {solid: true},
		silver: {solid: true},
		platinum: {solid: true},
		copper: {solid: true},
		titanium: {solid: true},
		bronze: {solid: true},
		cobble: {solid: true},
		plank: {solid: true},
		trunk: {solid: true},
		dirt: {solid: true},
		grass: {solid: true},
		sand: {solid: true},
		leaves: {solid: true, light: -1},
		weed: {solid: false, light: -1},
		red_flower: {solid: false, light: -1},
		yellow_flower: {solid: false, light: -1},
		water: {solid: true},
		slab: {solid: true},
		wood_stair: {solid: true},
		stone_stair: {solid: true},
		ladder: {solid: true},
		ice: {solid: true},
		glass: {solid: true, light: -1},
		lava: {solid: true},
		gravel: {solid: true},
		
		wood_pick: {solid: true},
		stone_pick: {solid: true},
		iron_pick: {solid: true},
		diamond_pick: {solid: true},
		uranium_pick: {solid: true},
		wood_axe: {solid: true},
		stone_axe: {solid: true},
		iron_axe: {solid: true},
		diamond_axe: {solid: true},
		wood_sword: {solid: true},
		stone_sword: {solid: true},
		iron_sword: {solid: true},
		diamond_sword: {solid: true},
		
		door_closed: {solid: true},
		door_open: {solid: true},
		player: {solid: true}
	};
	
	Crafty.sprite(32, "assets/Blockworld.png", Sprites);
}